params:
  epochs: 10
  batch_size: 32
  loss_function: sparse_categorical_crossentropy
  metrics: ['accuracy']
  optimizer: SGD
  validation_data_size: 5000
artifacts:
  artifacts_dir: artifacts
  model_dir: models
  plots_dir: plots
  checkpoint_dir: checkpoints
  model_name: ANN_Classifier
logs: 
  log_dir: log_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs 


